env: "local"
host: "localhost"
port: 3000
timeout: 4s
idle_timeout: 30s
app_secret: "taskify-secret"
app_id: 2

postgresql:
  host: "localhost"
  port: 5432
  user: "swiffy"
  password: "swiffy"
  name: "taskify"

clients:
  sso:
    address: "localhost:44044"
    timeout: 30s
    retries_count: 5